#!/bin/sh -f
###### This run file is generated by Pegasus UI
###### Pegasus Version 23.10-p015

## 		    Version 08 July 18, 2025			//

pegasus \
	--dp 4 \
	--log_dir LOGS \
	-top_cell darkio \
	-ui_data \
	--control ./fill_CTL.pvl \
	-interactive \
	/pdk/sky130_release_0.1.0/Sky130_FILLGEN/fillgen.v08.pvl

